openapi: '3.0.3'
info:
  title: Common Examples
  contact:
    name: API Integrations
    url: 'https://developer.globalpay.com/?gp-api=true'
    email: api.integrations@globalpay.com
  version: 2020 10 22
servers:
  - url: 'https://apis.sandbox.globalpay.com/ucp'
    description: Sandbox Environment
  - url: 'https://apis.globalpay.com/ucp'
    description: Production Environment

paths: {}

components:  
  examples:
    
    access_token_get:
      value:
        app_id: "i9R0byBBor6RqTQNj3g4MuVBwH5rd7yR"
        nonce: "random_string"
        secret: "e776ce1d9e94d5072ee132258e446cd92668d7c28b2e475a345319b475ba601956c16e3983926ce279db6301d78b7f47cfb729e41b4169814e373f0a0bf38716"
        grant_type: "client_credentials"
     
      
    access_token_with_permissions_get:
      value:
        app_id: "i9R0byBBor6RqTQNj3g4MuVBwH5rd7yR"
        nonce: "random_string"
        secret: "e776ce1d9e94d5072ee132258e446cd92668d7c28b2e475a345319b475ba601956c16e3983926ce279db6301d78b7f47cfb729e41b4169814e373f0a0bf38716"
        grant_type: "client_credentials"
        seconds_to_expire: 604799
        permissions:
        - TRN_POST_Authorize
  
    verification_request:
      value:
        account_name: "Transaction_Processing"
        channel: "CNP"
        currency: "USD"
        reference: "MY_TRANS_REF_12345"
        country: "US"
        payment_method:
          name: "James Mason"
          entry_mode: "ECOM"
          card:
            number: "4263970000005262"
            expiry_month: "05"
            expiry_year: "25"
    
    ECOMReq:
      value:
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CNP"
        amount: "1999"
        currency: "USD"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "US"
        payment_method: 
          name: "James Mason"
          entry_mode: "ECOM"
          authentication: 
            three_ds:
              server_trans_ref: "vJ9NXpFueXsAqeb4iAbJJbe+66s="
              value: "AAACBUGDZYYYIgGFGYNlAAAAAAA="
              eci: "5"
              message_version: "1.0.0"
          card: 
            number: "4263970000005262"
            expiry_month: "05"
            expiry_year: "25"
            cvv: "852"
            cvv_indicator: "PRESENT"
            avs_address: "Flat 123"
            avs_postal_code: "50001"

    EMVReq:
      value:
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CP"
        capture_mode: "AUTO"
        amount: "1999"
        currency: "USD"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "US"
        ip_address: "123.123.123.123"
        site_reference: "Site-1324"
        payment_method: 
          name: "James Mason"
          entry_mode: "CHIP"
          card:
            track: "%B4012002000060016^VI TEST CREDIT^251210118039000000000396?;4012002000060016=25121011803939600000?"
            tag: "9F4005F000F0A0019F02060000000025009F03060000000000009F2608D90A06501B48564E82027C005F3401019F360200029F0702FF009F0802008C9F0902008C9F34030403029F2701809F0D05F0400088009F0E0508000000009F0F05F0400098005F280208409F390105FFC605DC4000A800FFC7050010000000FFC805DC4004F8009F3303E0B8C89F1A0208409F350122950500000080005F2A0208409A031409109B02E8009F21030811539C01009F37045EED3A8E4F07A00000000310109F0607A00000000310108407A00000000310109F100706010A03A400029F410400000001"
            funding: "DEBIT"
            chip_condition: ""
            pin_block: ""
            brand_reference: ""
        
    Moto_Capture_Later:
      value:
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CNP"
        capture_mode: "LATER"
        amount: "1999"
        currency: "USD"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: US
        payment_method: 
          name: "James Mason"
          entry_mode: "MOTO"
          card: 
            number: "4263970000005262"
            expiry_month: "05"
            expiry_year: "25"
            cvv: "852"
            cvv_indicator: "PRESENT"
            avs_address: "Flat 123"
            avs_postal_code: "50001"

    Swipe:
      value:
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CP"
        amount: "1999"
        currency: "USD"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "US"
        payment_method: 
          name: "James Mason"
          entry_mode: "SWIPE"
          card: 
            track: "%B4012002000060016^VI TEST CREDIT^251210118039000000000396?;4012002000060016=25121011803939600000?"
            funding: CREDIT
            chip_condition: ""
            pin_block: ""
            brand_reference: ""

    Authorization_With_Payment_Token:
      value:
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CNP"
        capture_mode: "AUTO"
        amount: "1999"
        currency: "USD"
        reference: 93459c78-f3f9-427c-84df-ca0584bb55bf
        country: "US"
        ip_address: "123.123.123.123"
        payment_method: 
          id: "PMT_f6878e2a-2744-4d63-9420-3cc25c349ad2"
          name: "James Mason"
          entry_mode: ECOM
          authentication: 
            three_ds:
              server_trans_ref: "vJ9NXpFueXsAqeb4iAbJJbe+66s="
              value: "AAACBUGDZYYYIgGFGYNlAAAAAAA="
              eci: "5"
              message_version: "1.0.0"
             
    
    Stored_Credential:
      value:
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CNP"
        capture_mode: "AUTO"
        amount: "1999"
        currency: "USD"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "US"
        payment_method: 
          id: "PMT_f6878e2a-2744-4d63-9420-3cc25c349ad2"
          name: "James Mason"
          entry_mode: "ECOM"
          
        initiator: "MERCHANT"
        stored_credential: 
          model: "SUBSCRIPTION"
          reason: "INCREMENTAL"
          sequence: "SUBSEQUENT"

    apms:
      value: 
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CNP"
        amount: "1999"
        currency: "EUR"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "US"
        payment_method: 
          name: "James Mason"
          entry_mode: "ECOM"
          apm: 
            provider: "testpay"
        notifications: 
          return_url: "https://www.example.com/return_url"
          status_url: "https://www.example.com/status_url"
    
    apm_paypal:
      value: 
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CNP"
        amount: "2999"
        currency: "EUR"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "GB"
        payment_method: 
          name: "James Mason"
          entry_mode: "ECOM"
          apm: 
            provider: "paypal"
        notifications: 
          return_url: "https://www.example.com/return_url"
          status_url: "https://www.example.com/status_url"
          cancel_url: "https://www.example.com/cancel_url"

    ecom_refund:
      value:
        account_name: "Transaction_Processing"
        type: "REFUND"
        channel: "CNP"
        capture_mode: "AUTO"
        amount: "1999"
        currency: "USD"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "US"
        ip_address: "123.123.123.123"
        payment_method: 
          name: "James Mason"
          entry_mode: "ECOM"
          card: 
            number: "4263970000005262"
            expiry_month: "05"
            expiry_year: "25"
            cvv: "852"
            cvv_indicator: PRESENT
            avs_address: "Flat 123"
            avs_postal_code: "50001"
    
    cardpresent_refund:
      value:
        account_name: "Transaction_Processing"
        type: "REFUND"
        channel: "CP"
        capture_mode: "AUTO"
        amount: "1999"
        currency: "USD"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "US"
        payment_method: 
          name: "James Mason"
          entry_mode: "CHIP"
          card: 
            track: "%B4012002000060016^VI TEST CREDIT^251210118039000000000396?;4012002000060016=25121011803939600000?"
            tag: "9F4005F000F0A0019F02060000000025009F03060000000000009F2608D90A06501B48564E82027C005F3401019F360200029F0702FF009F0802008C9F0902008C9F34030403029F2701809F0D05F0400088009F0E0508000000009F0F05F0400098005F280208409F390105FFC605DC4000A800FFC7050010000000FFC805DC4004F8009F3303E0B8C89F1A0208409F350122950500000080005F2A0208409A031409109B02E8009F21030811539C01009F37045EED3A8E4F07A00000000310109F0607A00000000310108407A00000000310109F100706010A03A400029F410400000001"
            funding: "DEBIT"


    digital_wallet_apple_tokenized:
      value:
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CNP"
        capture_mode: "AUTO"
        amount: "1999"
        currency: "USD"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "US"
        payment_method: 
          name: "James Mason"
          entry_mode: ECOM
          digital_wallet:
            provider: "APPLEPAY"
            payment_token:
              version: "EC_v1"
              data: "Ft+dvMNzlcy6WNB+zerKtkh/RWW4RWW4yXIRgmM3WC/FYEC6Z+OJEzir2sDyzDkjIUJ0TFCQd/QAAAAAAAA=="
              header: 
                  ephemeralPublicKey: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWdNhNAHy9kO2Kol33kIh7k6wh6E/lxriM46MR1FUrn7SHugprkaeFmWKZPgGpWgZ+telY/G1+YSoaCbR5YSoaCbR57bdGA=="
                  transactionId: "fd88874954acdb299c285f95a3202ad1f330d3fd4ebc22a864398684198644c3"
                  publicKeyHash: "h7WnNVz2gmpTSkHqETOWsskFPLSj31e3sPTS2cBxgrk="
                
    digital_wallet_apple_detokenized:
      value:
        account_name: "Transaction_Processing"
        type: "SALE"
        channel: "CNP"
        capture_mode: "AUTO"
        amount: "1999"
        currency: "USD"
        reference: "93459c78-f3f9-427c-84df-ca0584bb55bf"
        country: "US"
        payment_method: 
          name: "James Mason"
          entry_mode: ECOM
          digital_wallet:
            token: "5167300431085507"
            token_format: "CARD_NUMBER"
            expiry_month: "12"
            expiry_year: "20"
            cryptogram: "234234234"
            provider: "APPLEPAY"
            eci: "5"        

## Authentications
## Authentications 3DS 1
    authentication_3ds1_check_availability_challenge:
      value:
        account_name: "Transaction_Processing"
        reference: "3ds1_ref1"
        channel: "CNP"
        amount: "6089"
        currency: "EUR"
        country: "FR"
        payment_method:
          card:
            number: '4012001037141112'
            expiry_month: '12'
            expiry_year: '25'
        notifications:
          challenge_return_url: "https://ensi808o85za.x.pipedream.net/"
          three_ds_method_return_url: "https://ensi808o85za.x.pipedream.net/"

## Authentications 3DS 2
    authentication_3ds2_check_availability_challenge:
      value:
        account_name: Transaction_Processing
        reference: 3ds2_ref1
        channel: CNP
        amount: '5089'
        currency: EUR
        country: FR
        payment_method:
          card:
            number: '4012001038488884'
            expiry_month: '12'
            expiry_year: '25'
        notifications:
          challenge_return_url: https://ensi808o85za.x.pipedream.net/
          three_ds_method_return_url: https://ensi808o85za.x.pipedream.net/

    authentication_3ds2_initiate_challenge:
      value:
        method_url_completion_status: 'YES'
        source: BROWSER
        merchant_contact_url: https://enp4qhvjseljg.x.pipedream.net/
        order:
          time_created_reference: '2019-04-26T10:19:32.552327Z'
          amount: 5089
          currency: EUR
          reference: 3400dd37-101d-4940-be15-3c963b6109b3
          address_match_indicator: 'false'
          shipping_address:
            line1: Apartment 852
            line2: Complex 741
            line3: House 963
            city: Chicago
            postal_code: '50001'
            state: IL
            country: '840'
          gift_card_count: '01'
          gift_card_currency: EUR
          gift_card_amount: '25000'
          delivery_email: james.mason@example.com
          delivery_timeframe: ELECTRONIC_DELIVERY
          shipping_method: ANOTHER_VERIFIED_ADDRESS
          shipping_name_matches_cardholder_name: 'true'
          preorder_indicator: MERCHANDISE_AVAILABLE
          preorder_availability_date: '2019-04-18'
          reorder_indicator: FIRST_TIME_ORDER
          category: GOODS_SERVICE_PURCHASE
        payment_method:
          card:
            number: '4012001038488884'
            expiry_month: '12'
            expiry_year: '25'
        payer:
          reference: 6dcb24f5-74a0-4da3-98da-4f0aa0e88db3
          account_age: LESS_THAN_THIRTY_DAYS
          account_creation_date: '2019-01-10'
          account_change_date: '2019-01-28'
          account_change_indicator: THIS_TRANSACTION
          account_password_change_date: '2019-01-15'
          account_password_change_indicator: LESS_THAN_THIRTY_DAYS
          home_phone:
            country_code: '44'
            subscriber_number: '123456789'
          work_phone:
            country_code: '44'
            subscriber_number: '1801555888'
          payment_account_creation_date: '2019-01-01'
          payment_account_age_indicator: LESS_THAN_THIRTY_DAYS
          suspicious_account_activity: NO_SUSPICIOUS_ACTIVITY
          purchases_last_6months_count: '03'
          transactions_last_24hours_count: '01'
          transaction_last_year_count: '05'
          provision_attempt_last_24hours_count: '01'
          shipping_address_time_created_reference: '2019-01-28'
          shipping_address_creation_indicator: THIS_TRANSACTION
        payer_prior_three_ds_authentication_data:
          authentication_method: FRICTIONLESS_AUTHENTICATION
          acs_transaction_reference: 26c3f619-39a4-4040-bf1f-6fd433e6d615
          authentication_timestamp: '2020-07-28T10:26:49.712Z'
          authentication_data: secret123
        recurring_authorization_data:
          max_number_of_instalments: '05'
          frequency: '25'
          expiry_date: '2019-08-25'
        payer_login_data:
          authentication_data: secret123
          authentication_timestamp: '2020-07-28T10:26:49.712Z'
          authentication_type: MERCHANT_SYSTEM_AUTHENTICATION
        browser_data:
          accept_header: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
          color_depth: TWENTY_FOUR_BITS
          ip: 123.123.123.123
          java_enabled: 'true'
          javascript_enabled: 'true'
          language: en-US
          screen_height: '1080'
          screen_width: '1920'
          challenge_window_size: FULL_SCREEN
          timezone: '0'
          user_agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML,like Gecko) Chrome/70.0.3538.110 Safari/537.36
    
    authentication_3ds2_check_availability_frictionless:
      value:
        account_name: Transaction_Processing
        reference: 3ds1_ref2
        channel: CNP
        amount: '5089'
        currency: EUR
        country: FR
        payment_method:
          card:
            number: '4263970000005262'
            expiry_month: '12'
            expiry_year: '25'
        notifications:
          challenge_return_url: https://ensi808o85za.x.pipedream.net/
          three_ds_method_return_url: https://ensi808o85za.x.pipedream.net/

    authentication_3ds1_obtain_result:
      value:
        three_ds:
          challenge_result_value: eJzVWVmTo0iS/itttY+yHk5J0JaVY8EpkLhvvXGJWyAOgfj1G1JWdWfV9O707O48rMzSiHA8PDz8/CJ5+/vS1L/c034o2uvXL9jf0C+/pNe4TYpr9vWLYwu/Ul/+/v5m532aclYaT336/qakwxBm6S9F8vVLSmDkFk220SXekzssptNtfLlgux1NbKl9mn55f9OBmQ4v5h2JUjSBEhSkftvzHW75N/wN+T6Fwvs4D6/j+1sY3xhJfSf3JEZTb8i36VuT9hL3Tn/7vSEf8zfkj4X69BwNUNOlSN65DVkGbJ0oYHGPXR40j0ZoMX5w+PbrG/LkeEvCMX3HURxDCXz3C0b+RmC/kdgb8qK/dU9xoGknKJtGUfQN+Ux5gzbpocke7/Qeavn77C1duvaaQg54ut/Hb8gfynXh9Z1EMRxF4b57jMQwDLI+qW+2//42Fs1npba/EfhvJGR40d+GMRyn4T14Q76N3uLwfn8HADBArLrYAK9fxtbLxwjAw75Y3tK4eEe3UCn4fK0Cddb2xZg3T1V/JLwhT1WQlwvf36wiu8LN+vQXGDXX4euXfBy73xBknue/zcTf2j5D4GlQBKURyJAMRfYfXz5WpYl0vbTvb2x4ba9FHNbFGo7Q30o65m3yy+8b/plI23xKxRCTZ3+FYn+NMfL664fVsO0X5JNaf0Xazwr2Q/jrkIfYU5CZXtKn99JfHFP6+uU/PscrV2TpMP5Pdvgu/UOCG9ZT+o7lymzl12FeJbzmypCoZJCLpeqoJPTTZ8435Het4PizLX8/9gejl8WlfeiPyIAN2nV3jSudXvfD7S5qKjdtW1VdTq57uGcRGWzaBuUlLkzP2Fj5a9QOuHJMVYMuHymRGXl/GEjWoYnIcvCdeb0jzY6qjlOzTIM/n729H2euUkUdExhO7Fk0u+aExSw6e6n4FLgiQHIrj/imyBtRlefF5W+a2M2DJUnkiSqpxQvvU+oiM+OZ9qxU8w7cZ0nkkxaxnWGwfFEGe0IZaQdncyQBwgb0pRU35XZjOaiJssnCtouA0KnhR3sgLGrWyS3YnDvKv2xXJDGNaBT5DdlfOvphuZjJac5ZpatJ3Q3LpBNehewE1tlSPRii1rZabCLA0ZciVyCo3gHepUcq/FJkX79+GP2Tod+O6ePDA/4WpblwDD9GbNqPxQUGNywaiiSJos2yjCFmYJYYkEm2BHNSKi6WdJvwFB/EfgYczMtCXoHKZNUtrwqRnlEGGIMA3+wUU5l5IziyZ6kpzvrjJBqMaAZcgNOjYhozn/3DOz7y3V208qoCBhFgDg8WhY88tQxskAoz+lBs8FBKZVFtaVHsJHzR1h9pCh8v7ApkJlNdBsCVlRoqxjyzWcC5hnHkZ/Xg8M7Cc0D74BlsBjXrpKnLs68sIge8D7picwSTpxa2hh46xnh9jZp6Oq8sCyxp5oxAPrZnKb/HKjB4hjEAl2W8Djj43mhZOIYihHTorB1yv2ridVW14HRriOvxPDWOqsytWHAEMmH2kiuVEuWrk23zZGkiIyStmTtRPtlAh1DMnQfT1cASdzPcVYxqg/qGNtFj9aww746OyOEABVNyt0sHnTDLDK+4WJNzocWl3AuTU/eHaH+mtiqbFQiIw7TzSHTj+XtyOTiBbBHezGAPG2f1qFCBl2d0391c/8qju46vzDSrD2faQpUk2WJq3e2UU43pYhXEtwgt85BdJ301mcwPyKSoSD6iFw9hK98xcMPrOiD36rzZuloEDJcVfB8dvGN52oebibpIh+gWmgM9T+magsED/aXpPKepakzEV/6yMWO37c+E1Ld5oG0tR6hQFsw8AKEGn9WcZYqgMOgzXhIuMzzoCK4400PjiElzRsrjfj/RLnvXO4x3V3B5+vZgKfzTzxljzkorsslASWDaghJxxNpIqkip0M5++rF6yT3MFhyDObug8O+WZZcU/lliFrrDWRRmraDuJ1TVdA8rA5wfDJSkbUflDGvh7BLjTAG8aM7BLSKxLmVbmi3c3T6fDu4+vsXeB89PcwOnpzPsV4kv54lY36Ni4Y0VGxO/u594k9M99R7ZNOSX0dA7dwEuoGdXhvFMl4FvdhG+VUJfRXVczmPcQSJcvp09FTXwJY8JhQ4wWTHFek0OchdcXSiDnhyR7qKrJR7FHE0OYHd60KqBqsypwbC0oaZnDsPz1vHVFKKrfI/E+f7KU2tbxs1DlP5Y96RdY9GZAqK9x/D8p6cc/GUnSJMHWGuYwxxIxzmArnMOMJd4mDvmk87ZLNOCP94p4ChmZ/W/tLnh1MyJhzSXwYJm6YKH81D4sU4t+BSe+j7t464fPD/NHWjH5tydCffxYTdyMHmFftWkx8vmZYSjSIAK3A+2tuki8NVax+kibNwy4dUBzlfol6d9Oui7735gEt9sI0LukkM1q/OP5zri/6qts/X4tPfVmE8/yZLwv2T/VnlUTx+g3+ptws0GD+s9T3FgA2t6z2Q8D81PCEbMw9p7Z4r4E63gx3Ss8mR/cqXTuV40bjOaQzYhwJd4M98TndUesbJwWOAZMH+U+WDAGmyiNcMEs/DJrzCfRZaFOhiOwMwKq7CxyFrPucFkZeyymREqTPas4Z/X/DT/h5p8+laTGXCapu1dG4PS3KDjBqTRop2o1ccfrJh7dXYjQ3Orx5UptjiiwcKUl3IdT9zlcb4V+2FtFpu0NDoSkXQiZm3DizJvdxGHyREm2cFVTQKxoxrWzzyqakSF17MjLHigHC5SjpMX/EBfznh+JTYJI3iKoGOct+63+/NOs2OSj2MijRUGx25x4a5uTHLufS2vVFbLySPp0CnYPnSEdJs9D46H9Vgb8QGxcs6tL1TYi0q1ZUOLjfDROXPoY+l6epJrUic0KdgmVZKgfYk5FFkv8aGfJhGtM4hw1Ik98ph/Q2V77CZUDTdlieuTSYKs1CfX8fqDRq/8bDGsGhdknnCxaghO9dD9paii292YIbj4GTn8GZQ4oE8oETXfocQxsEz6mEGoD3/sn8OHzf8CPpgKoL7DB+mVKj5MG8KYD3msKnYwKyV4QokVPlfvSSt/p6EvWvl/DV/+FcgwbNSJboXy8JCdI9XX0op22OPe+4N8a82090omLvMivpNRRNFhX2pElV8PGEB9gww5vR8Qx9s6rpZUg97rC3Mvb1W0SPbqNOqhmuo7sr+RHl8H1uFabrhd5ZuSX4AEtM1dyOS8xYAWWTR9qy+uIE+iCjohl7Paz86a5EfrXsY8DbFuwljNoXA7mzdZdrrD2ljn+UBUZSCo6u1eRWDQJ93yFIRZu83mfs5adGuOu+TeCPbl9Ng2va/aBBfZLm9EPRbbMYuyS7Wl/YFSSzSOck3nSOI6LMmVuyhM2mn33cUqyoWlhnTdM1kShDWELFSJ0Xs2DG08X+ZzjzT4pjiqhbM3HGdLLFNsU39ABlqBkEHXv8VIws88g8yGoACFARfqe4nSYInihQN4ZIGMr3PG7itWp43QZXBzeNhW/VPJZPISGD+WTP5FBysof6RLvJAZTlDBFN2bLsfQzjrKbKGEhVYz9UgGszO/dMgYfp6tkpFg5ftYf5E2IBB6GDuzxgGcybInXWCMmAVmcAsPJhpz7f2Eq/mpSeYzbA9pQc+JJ90NVDAiHLZEorrDtjV/G09wzagw1edy64DMUA5ZCxyICoEoAWNmGIX5sJc0G4HChEA4XWlpx0qqScSi6DYOUp+HDISnM+0+W7f5YccLA8f6M77tDNqdR1s4V47PfHhA+IT9SSsXHhFOo6+W/PPcUXmHfUEqI/HkIfSUWimZ09mvnk8btmU8fLbdx4vn5zkHW3ATegkWN8IL5nzAp1ebfbX6Z27r+A9tu3YaF4+gPV/Qq1q6mDCQoBFW2PbvQdPVAWFykSisMYQHTrXwT6gVN3WRfLR8aPN6SqSg+u99w98/1akXLMoLeFM/mC/bBLhZP+HSq77gavVcC6EIpP/Zuu6HdQmhYvFj+4KLz/mpgTDHesICegygLnFD3xP2Cdtm6B+B/hRTsBZD2OtRT3qvSGL16d0M2pCp8aUK/CfMoO5P+PVJl/93cEz/CWYqfwnCfsSm/2l85PgO2viRcAz40V4B+ikGKgjB8w+IB6H7U/YT5j1j45/LZX+Si/8g10/WxFf+SayYl0++ahXrOwxEYR24iZYUERzsT+zsAEBKsDexyk2PvXqbMXeUacig36jbDQVG6Z6RmlLRCXXPNU3YLZorAVPbHlN52vQNanGaPpZmcZKpfJcXinKxlthUFJtoqAS6prAtziaWDssDBIK0Yx/SyOrXQXh2m9sNGnCQnK1yWFUsYY15WSPFucT1JCGkjx5DjqM5V6Y7IUro7HQYduWGwirgzTPCHqZCOcqJeEis4T6cHl50dLyoFOfzo4A5auHNcuqaDMlPaFGHN68RnFBEb8RtN6LFVdyTG4XWt9Mg3nq/LU2mqeXWo8oDl4jHy2W/1/DIBEBFRfySjKbAemfJnzOD3dMphEh8027hPVasSuF0vvproeHTtEtXKdWXY0gk5rE9nI76gVO9yVlRJK4a0sqXo7bgm01/SpmAOk4bYhbJhR/HpS6XzbHKwzva0iK2ldIwna+hka/KScgIomb2jl6K4+U87zxXZ6iyJLRl3EE4qC9eq1mRyjinWc81itM1cbDTwgtExpuVmSkwOfDOyLU3b+U1ami/6K56i5z1YruZLo4g2KSAFtiFQfVIuBMEn2DWw3TOoD4Eq9UbtzY6baax4AL7MObD0JWp7G8zqQMHs+Jd2Q8KmJR5WOaHUt0KF4FvnMoixUE0jGi3j2931UH90eQP4X6z8iN5RGTj2B0D9KpxpwaXWEGWg5y0ZvHI3/zEmZGaqxD6drhM8W01h6EHe1Vd3MI2t8oiVMbXvwhLhcuzLeHWd1hqhBrPkZVsrPvzwSrCSIEFYVv+DE+dfy885YJFsSVSsflZWQ3iBU9XyFkCSJNWdXUwCE//LftnmVT8XALgeV8lgJvB8/0RtM9ywN0kflhxQBG5eKv1h2UWS3XnowAHVy9Z4V3ClkSD3OKtazgoUg+oqgt4NVU6qvXC6XGtwQLz5CZirlTWOy/MtsuZMbWuLyUGPyZ7Ih4D/cH4wGJ0fQCXsHfHzjeLVi+HIL/dfdQp/GkSyGpIbE0hKUDqY44/xEiejT2lqBvL8CeqWHYmY5Z5GFkXI9fockmMG22PgfVQp26bK/DQRxI53Okt1+n0fiqLxx47KzvH3tY1yprsmtAzJQwnZo8lj3Bqtg+cIpCT214DabgcQbExsQBt92fX9KSbt+M421ldpbRJqgaouRzFsjZ6teeVbZ75FrrFz8k5wtZFbxR/f/e21yvYIAsRhV65MwQ1iS3i4tU26kp3eWkcVs1R5lFfS/aGWddHyhKzPQ5stuHEexIa2tFpsCAy70R5iJHCBuGeK+lq3FW7FEfFfH2wU06vvQP4ZiG8pmPxZME0XrdKYqvO5266ywlCzLN3VlW3qO5ZV1L22o0thjLbqU0SOTB2ifDA6Vq/yYFkjq24kW5mp0VJYUxbbaxrYbVYOXF6J3L6+DGRJLnV1Rk/VaXVQux7PiAU/qCY4/myOhAuUkyEZpeZcG17L3l4oBZa1EcNG28QeHPiTNGYqROvJSss3fJeukNsdTUuqtcgHRLI6oohqSQP84k6KD0aHQU7ck2fKDMjErRrbgZ66qeueuVJv9OpyZA4YACmJYI54cDp9d8/g3res1gQBDP3AbVtYBwQBgJe8LwOrCD54CNfUH26oGUrZdghmYOzd7Y3bvOAEscr5sBLBbzSPWEDEFl1cZiXXAjPpfkHOvu6TsjJuJnJuo1w8eQu2XZ/X6MUw1rMHn/OO8b4vfXGNRkNzSBNZ8lI67w42I8kb710uiiDfkRWq+uT3Ozuq3vDTnHTssI1OCwj8Tgr43BV2Y1InZDd4Xhci0bghYAkd8PjvPaPterLCV+hsScpJ1DNFt3AHQAr4fR8k9dDnUyTjcDGG1+Rk6rI535bXmVZ7Q1tK1tXdN3fY+l4t+3udmiV0Rt5a1XOpbz3MrFxkQCjqDY7uGKH2lqVcOn5enJ7YqMPmZ94LpIMR/FQw1RqNX9RxjiojvGJBLpqukXo1DlGKVgV5zyEr/dT2430eLS5XAZEIksFbIxiLd8GGUl9gC5HOkEbvZ8I77BoEiImQsttTZ9qkZApIl0vvWV/v8YlzeRsOiDmrh37jMCp7dYwDvJCokFk10hNhpiwIW/8NiHQnddOYb4ZSSuTLxoT+oGhiXFpR6V319Q0wgIpTuHt5ehOm/NRElTxvAd0rAZhpURXMUH7xyWyYyqWFdSnjqqNyjehZfa3/bGedg/hgl81DDTAbfKiWpc0Own8eJ9b0WbVRKJaxTdY5MHmxL5z2KJmaUeTPeGEUK2jrxZmU1UYh5J6VXpkjxJMguwYGG6DcV0LOr9dxvlgbq19tielhqHOxSLaMk3yztJrKeYsBlef9rfjY2L71SN5XlOnGF68CbIehx1+kSXQFems83Mc73haQjGSyJmBDs+E3gyzwyLlvlR8NHVyptiVCA90mannP229yB/fmZDfvz398VXq9e379UX++bn285f6/wRet4RH
          

    authentication_3ds2_obtain_result:
      value:


    ach_sale:
      value:
        account_name: Transaction_Processing
        channel: CNP
        type: SALE
        amount: '12345'
        currency: USD
        reference: '67396831'
        country: US
        payment_method:
          name: Jane Doe
          entry_mode: ECOM
          bank_transfer:
            number: '1234567890'
            number_type: SAVING
            check_reference: '123'
            sec_code: WEB
            merchant_notes: '123'
            bank:
              code: '083908420'
              name: First Union
              address:
                line_1: 12000 Smoketown Rd
                line_2: Apt 3B
                line_3: X
                city: Mesa
                state: AZ
                postal_code: '22192'
                country: USA
        payer:
          name: ANGELA SMITH
          reference: '123'
          date_of_birth: '1967-08-13'
          landline_phone: '235555'
          mobile_phone: '222222'
          billing_address:
            line_1: Address Line 1
            line_2: Address Line 2
            city: PUNE
            state: AZ
            postal_code: '411015'
            country: USA

    ach_refund:
      value:
        channel: CNP
        type: REFUND
        amount: '12345'
        currency: HKD
        reference: Test_1234sd
        country: HK
        payment_method:
          name: Jane
          entry_mode: ECOM
          card:
            number: '4263970000005262'
            expiry_month: '09'
            expiry_year: '22'


## Payments Methods
## Create a Stored Payment Method
    create_payment_method:
      value:
        usage_mode: MULTIPLE
        reference: "card-1"
        card:
          number: '4012001037141112'
          expiry_month: '12'
          expiry_year: '25'
          cvv: '456'
  
## Create a Single Use Stored Payment Method
    create_payment_method_single:
      value:
        usage_mode: SINGLE
        reference: "card-431"
        card:
          number: '4012001037141112'
          expiry_month: '12'
          expiry_year: '25'
          cvv: '456'





        

